sudo: true
dist: trusty
addons:
  apt:
    update: true
    
language: node_js
node_js: 8.9

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  chrome: stable

install:
  - npm install

script: xvfb-run npm test
